### PR TITLE
Testing base, ES6 coverage report

### PR DESCRIPTION
**Pull request by nkbt**
As part of #13.
Independent from the code itself. Only had to fix same syntax issue in Spring, since parser crashed on that one.

When lib files are moved, these configs should be updated accordingly, but for the moment everything works fine.

### CODE REVIEW

**Comment by nkbt** [comment]
## Tests run
tests

## Coverage report

**Comment by chenglou** [comment]
I'll hold this off since we don't need jasmine, karma and code coverage right now. License's a no-brainer though.

**Comment by nkbt** [comment]
No problem, it's quite isolated, so can be added anytime. If you prefer
another stack, let me know. Mocha, testem, tape, etc.

I recommend to solve this sooner then later, so it will be easy to write
tests and encourage contributors to increase coverage.

**Comment by iclanzan** [comment]
I would also love to see this solved asap. I personally prefer Testem + Tape, but anything will do.

**Comment by chenglou** [comment]
Let's do mocha for now because it's the one I'm familiar with. We can check into the alternatives later.

(cc @dariocravero who had a huge PR with some tests)

**Comment by gaearon** [comment]
In my experience Mocha is amazing, + Karma if you need DOM.

**Comment by chenglou** [comment]
:+1 If you say so! Don't think there's enough DOM-related logic so we can keep karma for later. Mocha it is for now then!

**Comment by nkbt** [comment]
Deal, will use Mocha and update PR asap.

**Comment by chenglou** [comment]
@nkbt can you keep karma and coverage out for now?

**Comment by nkbt** [comment]
@chenglou sure, no karma. That was just a rebase commit.

**Comment by nkbt** [comment]
@chenglou why not coverage? It works pretty well. The only thing I needed to do is to rename Spring.jsx to Spring.js, so it appears in coverage report (spent decent amount of time trying to find workaround to get report for js and jsx, messing with isparta and istanbul, but found the best solution is just to rename it to js)

**Comment by chenglou** [comment]
Meh. I guess we can keep coverage for now. When you're done, please squash and I'll merge

**Comment by nkbt** [comment]
Squashed.

**Comment by chenglou** [comment]
:+1: thanks!

**Comment by nkbt** [comment]
Great!

**Pull request merged**
