### PR TITLE
Demos: Clarify how to interact with spring paramters demo :)

### PR DESCRIPTION
**Pull request by daedelus-j**

### CODE REVIEW

**Comment by chenglou** [comment]
screenshot please?

**Comment by daedelus-j** [comment]
https://www.evernote.com/l/AdeMx2R9sBFGs4O_xsYO6VM7eVMu9_XMV1Y

**Comment by daedelus-j** [comment]
skitch 2

**Comment by daedelus-j** [comment]
can add italics and unbold if you want, keep it minimal.

**Comment by chenglou** [comment]
Nope, that's good enough! Thanks!

**Pull request merged**
