### PR TITLE
Reexport flow types from src

### PR DESCRIPTION
**Pull request by TrySound**
This way allows to avoid copying source files and just reuse them for flow types.

If you don't have enough time to maintain this project, I could take care at least about build step and make output smaller. This is important for me since this project is a dependency of [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L50)

/cc @chenglou @nkbt

### CODE REVIEW

**Comment by TrySound** [comment]
Ping guys. I want to make this project even better. 

Here's example of my open source work https://github.com/bvaughn/react-virtualized/commits?author=TrySound

/cc @chenglou @nkbt

**Comment by TrySound** [comment]
You guys suck in maintaining so popular project.

**Comment by nkbt** [comment]
Yep, I certainly do. Life and things, you know ¯\_(ツ)_/¯
-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by kentcdodds** [comment]
> I want to make this project even better.

That's great!

> You guys suck in maintaining so popular project.

Please don't say things like this. It's never appropriate and is a total jerk-move. Instead you could ping the maintainers again and offer to help maintain the project. If you still get no response then a fork would be appropriate (and perhaps a merge in the future).

I hope you all have a better day :)

**Comment by chenglou** [comment]
Removing such a dependency is nice. Thanks for the PR @TrySound. I'll merge it. Sorry for the long wait

**Comment by TrySound** [comment]
Yay. Cool. That worked. Sorry for my words.

**Comment by chenglou** [comment]
All good =)

**Pull request merged**
