### PR TITLE
Maintain the same build file paths

### LINKED ISSUE #577: Need to maintain same build file locations
We used to have `lib/react-motion.js` and `build/react-motion.js`, current partially completed move to rollup puts files into a different dirs, so we cannot publish patch version. 

I will do an update asap to keep build artefacts in old spots so we do not introduce unnecessary breaking change

### PR DESCRIPTION
**Pull request by nkbt**
Closes #577

Had to update all the babel stuff, so versions match, I've tested new built version with my other app and it looked good. If anyone can try this too - would be nice.

## Notes
- **removed** `./build/react-motion.map`. I am not sure it ever worked, please let me know if it **not safe** to remove it (I feel like it is ok to not have it)
- **added** `./build/react-motion.min.js`
- **added** `./src/*` all source files, good to have when you have your own special build

## Currently published version
```sh
find ./node_modules/react-motion
./AUTHORS
./bower.json
./build
./build/react-motion.js
./build/react-motion.map
./HISTORY.md
./lib
./lib/mapToZero.js
./lib/mapToZero.js.flow
./lib/mergeDiff.js
./lib/mergeDiff.js.flow
./lib/Motion.js
./lib/Motion.js.flow
./lib/presets.js
./lib/presets.js.flow
./lib/react-motion.js
./lib/react-motion.js.flow
./lib/reorderKeys.js
./lib/reorderKeys.js.flow
./lib/shouldStopAnimation.js
./lib/shouldStopAnimation.js.flow
./lib/spring.js
./lib/spring.js.flow
./lib/StaggeredMotion.js
./lib/StaggeredMotion.js.flow
./lib/stepper.js
./lib/stepper.js.flow
./lib/stripStyle.js
./lib/stripStyle.js.flow
./lib/TransitionMotion.js
./lib/TransitionMotion.js.flow
./lib/Types.js
./lib/Types.js.flow
./LICENSE
./package.json
./README.md

cat node_modules/react-motion/package.json | jq .version
"0.5.2"
```

## This change
```sh
$ npm pack
react-motion-0.5.2.tgz


$ npm install "<...>/react-motion/react-motion-0.5.2.tgz"
<...>
+ react-motion@0.5.2
added 10 packages from 48 contributors in 2.211s
found 0 vulnerabilities


$ find ./node_modules/react-motion
./AUTHORS
./bower.json
./build
./build/react-motion.js
./build/react-motion.min.js
./HISTORY.md
./lib
./lib/mapToZero.js
./lib/mapToZero.js.flow
./lib/mergeDiff.js
./lib/mergeDiff.js.flow
./lib/Motion.js
./lib/Motion.js.flow
./lib/presets.js
./lib/presets.js.flow
./lib/react-motion.js
./lib/react-motion.js.flow
./lib/reorderKeys.js
./lib/reorderKeys.js.flow
./lib/shouldStopAnimation.js
./lib/shouldStopAnimation.js.flow
./lib/spring.js
./lib/spring.js.flow
./lib/StaggeredMotion.js
./lib/StaggeredMotion.js.flow
./lib/stepper.js
./lib/stepper.js.flow
./lib/stripStyle.js
./lib/stripStyle.js.flow
./lib/TransitionMotion.js
./lib/TransitionMotion.js.flow
./lib/Types.js
./lib/Types.js.flow
./LICENSE
./package.json
./README.md
./src
./src/mapToZero.js
./src/mergeDiff.js
./src/Motion.js
./src/presets.js
./src/react-motion.js
./src/reorderKeys.js
./src/shouldStopAnimation.js
./src/spring.js
./src/StaggeredMotion.js
./src/stepper.js
./src/stripStyle.js
./src/TransitionMotion.js
./src/Types.js
```

# Visual diff
image

### CODE REVIEW

**Comment by nkbt** [comment]
Found that babel does not process modules and we end up with es6 modules in `lib/`. Working on it

**Comment by nkbt** [comment]
Babel build updated, here is the diff (old left, new right) for one of the small modules. Looks good now.

image

**Comment by chenglou** [comment]
I'm a bit out of touch here, so I'll just stamp this. Looks fine and thanks for your work, as always

**Comment by nkbt** [comment]
As nobody expressed any more concerns, I reckon it's good to go, we should be able to publish patch version without breaking anything

**Comment by theopak** [comment]
yay! thanks

**Comment by nkbt** [comment]
I cannot publish though.

**Comment by theopak** [comment]
ahhhhh, @chenglou would it be possible to publish?

**Comment by chenglou** [comment]
Humm I'm pretty sure @nkbt can publish? Am I misunderstanding this

**Comment by nkbt** [comment]
I’ll check that (will do some ‘next’ publish first to be sure). I thought npm was rejecting it long time ago, might have changed actually.

**Pull request merged**
