### PR TITLE
react-native 'compatibility'

### PR DESCRIPTION
**Pull request by threepointone**
tests pass, demos work, doesn't break regular web webpack builds.

I just want my name in this repo

### CODE REVIEW

**Comment by chenglou** [comment]
did you check that the `build/` version also works? Script tag require with global ReactMotion

**Comment by threepointone** [comment]
yes, just tested it, works fine. for posterity's sake, this was my file 

```html
<html>
  <head></head>
  <body>
    <script src="https://fb.me/react-0.13.3.js"></script>
    <script src='build/react-motion.js'></script>
    <script>
      console.log(ReactMotion);
    </script>
  </body>
</html>

```

**Comment by chenglou** [comment]
We should probably automate that check. Thanks!

**Comment by chenglou** [comment]
Humm webpack complains though. Is it possible to suppress the warnings? Like, extern react-native?

**Comment by gaearon** [comment]
@chenglou You can have separate export for React Native and turn components into factories. For example https://github.com/gaearon/react-redux/blob/master/src/native.js.

**Pull request merged**
