### PR TITLE
Use NPMCDN bower.zip package, fixes #250

### LINKED ISSUE #250: Use NPMCDN bower.zip package
https://twitter.com/mjackson/status/681150523634921472

### PR DESCRIPTION
**Pull request by nkbt**
Fixes #250

### CODE REVIEW

**Comment by chenglou** [comment]
So what's the magic incantation to make this work upon publish?

**Comment by nkbt** [comment]
As soon as it is merged and you published new version to npm (patch would be ok I guess), you can check it with 
```
bower install --save https://npmcdn.com/react-motion/bower.zip
```

Then obviously check the `bower_components` dir to make sure `react-motion` has right files in there (as well as dependencies: react)

**Comment by chenglou** [comment]
Sounds great to me! Thanks

**Comment by nkbt** [comment]
Publish new version on npm?

**Comment by chenglou** [comment]
Repo's currently undergoing some refactoring so I can't push yet. But we could theoretically revert to latest stable, put a new tag, then publish again... Does that even work?

**Comment by nkbt** [comment]
Yeah, why not. Works pretty well =)

**Pull request merged**
