### PR TITLE
lint fix : demo - demos

### PR DESCRIPTION
**Pull request by threepointone**
missing from #145

### CODE REVIEW

**Comment by chenglou** [comment]
Does this work? Just tested locally and it still doesn't work.

**Comment by threepointone** [comment]
Works for me?

**Comment by threepointone** [comment]
What error are you still getting?

**Comment by chenglou** [comment]
Did you try a fresh npm install? I think it's eslint again
```
.../react-motion/node_modules/eslint-plugin-react/lib/rules/prop-types.js:450
          propTypes.parent.type !== 'AssignmentExpression' &&
                          ^
TypeError: Cannot read property 'type' of undefined
```

**Comment by threepointone** [comment]
working just fine with a fresh npm install

**Comment by chenglou** [comment]
Humm that's weird. Switched to another laptop and now it works. Probably because of the artifacts of the `integration/` stuff which isn't tracked by this repo.

**Pull request merged**
