### PR TITLE
Add Motion.@onRest

### PR DESCRIPTION
**Pull request by appsforartists**
I don't intend for this to land until after I've used it and made sure we're solving the right problem, but I'm opening this now so @chenglou can play with it (and maybe add Flow if there are places I've missed).

See also #235.

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks a lot!

**Comment by appsforartists** [comment]
My pleasure!

**Comment by threepointone** [comment]
super!

**Comment by kumarharsh** [comment]
wow! awesome!

**Comment by leopoldjoy** [comment]
@appsforartists @chenglou Can this be used for `<Motion />`, `<StaggeredMotion />`, and `<TransitionMotion />`?

**Comment by chenglou** [comment]
@leopoldjoy currently only implemented for Motion, which is why I waited before the imminent public release, because I wanted it on all 3 components. But after discussing with people I've noticed that they only want it for Motion?

**Comment by leopoldjoy** [comment]
Yes, I agree that it seems like it's only really relevant to `Motion`. I was going to open a pull request for the `README.md` documentation as I found it extremely useful, would this be helpful/relevant?

**Comment by chenglou** [comment]
I'll publish it officially this week or next so don't worry about it.

**Comment by leopoldjoy** [comment]
@chenglou Ok, sounds good! Thanks for your work!

**Comment by sunflowerdeath** [comment]
onRest for TransitionMotion could be also very useful.

**Comment by haraldox** [comment]
@chenglou @appsforartists Great work guys! would be awesome to have that in master :)

**Comment by AlastairTaft** [comment]
Would be really useful to have this for `<StaggeredMotion />`. I'm trying to animate page navigation. Each page is made up of a handful of panels, maybe 3 or 4. When the user navigates between pages I want each panel to staggered-ly spring in. I need to know when the animation is done so that I can remove the old page component.

**Comment by ollwenjones** [comment]
Echo @AlastairTaft except for `TransitionMotion`

**Comment by appsforartists** [comment]
I don't think @chenglou or I use this library anymore, so if you do and you want `@onRest` for the other components, you should open a PR. 😃

**Comment by ollwenjones** [comment]
Is there a new flavor of the month for this kind of thing we should look at instead? 😜

**Comment by appsforartists** [comment]
I still like React Motion.  

I've got an experimental motion library that I use for my work, but it's not documented or published, which unfortunately makes it hard for other folks to use.

**Comment by ollwenjones** [comment]
Heh. How it goes for most of us, seems like. My use-case is a side-panel that squishes a map. Ideally, the map can be told to recenter/repaint after the squishing animation completes, but honestly I'm not sure anyone will notice it _isn't happening_ anytime soon. If it becomes an issue that makes it to the top of my backlog, then you can look for a PR from me. ;)

**Comment by kumarharsh** [comment]
See React-Spring or Popmotion (both are in active development). I haven't tried either yet, but they are on my todo list. 😄

**Comment by nkbt** [comment]
We still use react motion in many places. Though the only component that we work with is the main Motion, so I have no context/interest in modifying any other components.
((tbh I would be quite happy to have only that one available and not add up to the bundle))

**Comment by ollwenjones** [comment]
looks like popmotion/pose is a bit higher level, which is nice.

**Pull request merged**
