### PR TITLE
Fix unmounted state mutation

### PR DESCRIPTION
**Pull request by daniel-gustafsson**
TransitionSpring should likely have the same fix for unmounting that Spring element has regarding state mutation.

### CODE REVIEW

**Comment by chenglou** [comment]
@bsansouci

**Comment by bsansouci** [comment]
Good call!

**Comment by bsansouci** [comment]
Everything works! Thanks a lot.

**Comment by daniel-gustafsson** [comment]
Thanks for accepting it!

I wonder though if I made a mistake with the pull request, because I can't seem to find the actual commit in this repository anywhere. It was my very first pull request so apologies if I got it wrong.

**Comment by chenglou** [comment]
They're here alright: https://github.com/chenglou/react-motion/commit/30a780a2a4e5bb739c7c24191b268f675898c436 and https://github.com/chenglou/react-motion/commit/589ae9b3851442a165deb321a6039665a8e1672f =)

**Pull request merged**
