### PR TITLE
Use semi-implicit Euler integration.

### PR DESCRIPTION
**Pull request by iclanzan**
More accurate and much more stable. <https://en.wikipedia.org/wiki/Semi-implicit_Euler_method>

### CODE REVIEW

**Comment by iclanzan** [comment]
Consider the old code `const newX = x + v * frameRate;`. Assuming no initial velocity `x` would remain unchanged after the first step.

**Comment by chenglou** [comment]
Hah, physics =)
Curious though, how does this change make it "semi-implicit"? The wiki article's a bit hardcore

**Comment by iclanzan** [comment]
I don’t know why it is named “semi-implicit” but the difference to the standard Euler is that you use either the current velocity to to compute the current position or the current position to compute the current velocity. I chose the first approach to avoid the position staying the same after the first step.

Here are the methods exemplified in the context of our `stepper.js` file:

```js
// Euler integration
const newX = x + v * frameRate;
const newV = v + a * frameRate;

// Semi-implicit Euler (1st variation)
const newV = v + a * frameRate;
const newX = x + newV* frameRate;

// Semi-implicit Euler (2nd variation)
const newX = x + v * frameRate;
// Here you would need to compute the acceleration `a` using `newX`.
const newV = v + a * frameRate;
```

**Comment by iclanzan** [comment]
Also, the frameRate needs to be constant for best results with integration whereas right now the frameRate is all over the place because `requestAnimationFrame` does not fire at a constant interval.

For this reason it would make sense to decouple the stepper from rendering.
You might find this useful: <http://gafferongames.com/game-physics/fix-your-timestep/>.

**Comment by razh** [comment]
Following up on a related article, thoughts on using RK4 for integration: http://gafferongames.com/game-physics/integration-basics/?

Here's a visualization of RK4:
rk4_diagram
(source: http://drewskillman.com/thesis.html)

Example implementation (correct me if I'm wrong):
```js
const xa = x;
const va = v;
const aa = -k * (xa - destX) - b * va;

const xb = x + va * dt / 2;
const vb = v + aa * dt / 2;
const ab = -k * (xb - destX) - b * vb;

const xc = x + vb * dt / 2;
const vc = v + ab * dt / 2;
const ac = -k * (xc - destX) - b * vc;

const xd = x + vc * dt;
const vd = v + ac * dt;
const ad = -k * (xd - destX) - b * vd;

const dxdt = (va + 2 * (vb + vc) + vd) / 6;
const dvdt = (aa + 2 * (ab + ac) + ad) / 6;

const newX = x + dxdt * dt;
const newV = v + dvdt * dt;

return [newX, newV];
```

Where `frameRate` is replaced with `dt`.


If we add a helper for calculating acceleration:
```js
const acceleration = (x, v) => -k * (x - destX) - b * v;

const xa = x;
const va = v;
const aa = acceleration(xa, va);

const xb = x + va * dt / 2;
const vb = v + aa * dt / 2;
const ab = acceleration(xb, vb);

const xc = x + vb * dt / 2;
const vc = v + ab * dt / 2;
const ac = acceleration(xc, vc);

const xd = x + vc * dt;
const vd = v + ac * dt;
const ad = acceleration(xd, vd);
```

**Comment by iclanzan** [comment]
The RK4 is 4 times as expensive computationally and I don’t think that extra bit of accuracy is worth it. But I am not against it either.

**Comment by razh** [comment]
Did some quick testing, regular Euler integration never accumulates more than a few pixels worth of errors more than RK4 at the timescale/distances of most UI animations.

**Comment by chenglou** [comment]
Gosh this is interesting. I'll read through this soon. For reference, Rebound-js uses RK4: https://github.com/facebook/rebound-js/blob/fe8994c1caca9f0e7ff27336c5ecf0a4abd807dc/rebound.js#L601-L605

**Comment by chenglou** [comment]
Related: #31 which is causes by the weird time delta we get from browser slowing down rAF
Merging this. @iclanzan I'd love to decouple stepper from the rendering, gladly accepting PR =)

**Pull request merged**
