### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by johnamiahford**
Is there a way to target the `react-motion` channel specifically for the slack badge?

### CODE REVIEW

**Comment by nkbt** [comment]
I would think twice using slack for open source https://github.com/chenglou/react-motion/issues/33#issuecomment-120673921

**Comment by chenglou** [comment]
Wait I don't get how this diffed... The slack badge is already there. Weird?

**Comment by nkbt** [comment]
@johnamiahford hasn't rebased his branch

**Comment by chenglou** [comment]
Heh I thought that still wouldnt pass github's merge check. @johnamiahford can you rebase and add just the npm and bower badges please? Also, the existing slack badge should directly go to the channel already

**Comment by nkbt** [comment]
I can't join slack since no one invited me to reactiflux. Is it how it works?

**Comment by chenglou** [comment]
You don't need that (I know right, misleading...), just join with your email here: http://www.reactiflux.com

**Comment by nkbt** [comment]
Thanks. I'm too used to gitter

**Comment by johnamiahford** [comment]
Changed to shields.io badges to be consistent.

**Comment by chenglou** [comment]
Argh those orange badges scream "don't come near". This is almost literally bike shedding but, is there a way to have the green/blue ones?

Also, use flat instead of flat-square to be consistent with the Slack badge please

**Comment by johnamiahford** [comment]
Ha. I'll see if I can pretty these up for you.

**Comment by johnamiahford** [comment]
I've removed the bower package as it was returning not found. And went with the badge fury npm package as it gives us that pretty green we all love.

**Comment by chenglou** [comment]
Hmm that's weird, I'll take what's here then. Thanks!

**Pull request merged**
