### PR TITLE
chenglou/react-motion#507 performance-now update

### PR DESCRIPTION
**Pull request by penx**
Update performance-now to ^2.1.0

> react-motion has a dependency of performance-now@^0.2.0
> 
> It also has a dependency on raf@^3.1.0 which currently resolves to raf@3.4.0
> 
> raf@3.40 has a dependency on performance-now@^2.1.0
> 
> This means that including react-motion as a dependency introduces 2 major versions of raf.

chenglou/react-motion#507

### CODE REVIEW

**Comment by eaglus** [comment]
Please merge this PR into main branch, because now our project has multiple performance-now versions: 0.2.0, and 2.10, this is very bad for us!

**Comment by sgrishchenko** [comment]
Yes, this is a good improvement.

**Comment by lpagliari** [comment]
Hi, guys, do you have any updates on this? It is affecting our project too. Thanks!!

**Comment by chenglou** [comment]
Merged

**Comment by roderickhsiao** [comment]
Thanks all @chenglou would you mind to help release npm version for the fix? Or we are expecting more features to be released in the next version?

Thanks

**Comment by chenglou** [comment]
There hasn't been a release for a while now, and I kinda lost track of whether there were some breaking changes in-between. cc @nkbt @TrySound ?

**Comment by roderickhsiao** [comment]
https://github.com/chenglou/react-motion/commits/master Seems all build related code changes, nothing directly related to the core library itself.

- [ ] https://github.com/chenglou/react-motion/pull/536 Fix Link (document)
- [ ] https://github.com/chenglou/react-motion/pull/545 Update stack - webpack/babel (no user facing)
- [ ] https://github.com/chenglou/react-motion/pull/546 umd bundle 
- [ ] https://github.com/chenglou/react-motion/commit/407b98ea7ea90dd832dac126af097e6d3b3e00e3 Upgrade babel and build esm and cjs bundles
- [ ] https://github.com/chenglou/react-motion/pull/548 Upgrade babel and build esm and cjs bundles
- [ ] https://github.com/chenglou/react-motion/pull/549 Add prettier 
- [ ] https://github.com/chenglou/react-motion/pull/550  https://github.com/chenglou/react-motion/commit/1a7783835930560e02a60563edbe65d4b8c2a88c improve babel config (loose and class property)
- [ ] https://github.com/chenglou/react-motion/commit/dc40c5294d9f25e3ece53e362d05832b201a5a52 Remove babel-cli
- [ ] https://github.com/chenglou/react-motion/commit/4ccdd4dfe288554da6c5590ec2ca46c1e99065a4 Remove proptypes in prod
- [ ] https://github.com/chenglou/react-motion/pull/555 Remove phantomjs dependnecy

**Comment by roderickhsiao** [comment]
Oh there is two commit before this 

- [ ] https://github.com/chenglou/react-motion/pull/518 Fixed memory leak
- [ ] https://github.com/chenglou/react-motion/pull/533 export flowtyped

**Pull request merged**
