### PR TITLE
updated todos to show mounting animation

### PR DESCRIPTION
**Pull request by souporserious**
In response to this issue https://github.com/chenglou/react-motion/issues/137

### CODE REVIEW

**Comment by chenglou** [comment]
You could use `defaultValue`

**Comment by souporserious** [comment]
Thought it would be easier like that. Want me to update it using `defaultValue`?

**Comment by chenglou** [comment]
Yeah please do. using `prevValue` with a null check isn't intuitive. Otherwise I wouldn't have exposed `defaultValue`

**Comment by chenglou** [comment]
:+1:  thanks!

**Comment by wilfreddenton** [comment]
@souporserious with this commit should demo3 now animate in the todo items when the page loads/component mounts? I cloned the repo and ran it locally to see how to get the functionality in my project, but it's not animating for me.

**Comment by chenglou** [comment]
That's weird, it animates for me. Does your console say anything?

**Comment by souporserious** [comment]
Yeah works fine for me as well. You did `npm start` right?

**Comment by wilfreddenton** [comment]
Doh! Idk why I thought the demos would come transpiled. It's working for me. Thanks. I'm curious though, is it possible to also have unmounting animations? Like if there was some boolean that mounted and unmounted the list view.

**Comment by chenglou** [comment]
The demo actually does unmounting animation, when you filter through it or remove one

**Comment by wilfreddenton** [comment]
Right, it handles the unmounting of the individual list items. I was wondering if it could handle the unmounting of the containing unordered list but I see now that it's a better idea to just remove the items instead of the whole view when I want the list to disappear. This way the mounting/unmounting is all handled by react-motion. Thanks @chenglou and @souporserious so much for taking the time to help me!

**Comment by chenglou** [comment]
Right, there's no magic render-that-keeps-child. I've put this as a FAQ in the readme since it's not the first time I've encountered this question. Thanks!

**Pull request merged**
