### PR TITLE
Upgrade stack

### PR DESCRIPTION
**Pull request by TrySound**
I wanted to upgrade only babel but everything else was broken so I
upgraded babel, webpack, eslint and karma.

Disabled a lot of eslint rules to not change existing code. Maybe it's
better to migrate to prettier later.

This changes will unblock me from providing smaller output.

### CODE REVIEW

**Comment by TrySound** [comment]
We need to rerun travis

**Comment by TrySound** [comment]
Friendly ping @chenglou

**Comment by chenglou** [comment]
Thanks for the ping. To be clear, is there a user-facing change here? Or just for us devs?

**Comment by TrySound** [comment]
@chenglou This one only for devs.

**Comment by TrySound** [comment]
Bundle is slightly changed with new versions but I don't think there's anything significant.

**Comment by TrySound** [comment]
@chenglou Tests are passed.

**Comment by chenglou** [comment]
If there's no user-facing impact then sure. Thanks!

**Pull request merged**
