### PR TITLE
Add .babelrc

### PR DESCRIPTION
**Pull request by nkbt**

### CODE REVIEW

**Comment by chenglou** [comment]
I think it's safe to enable babel loose mode?

**Comment by nkbt** [comment]
Loose mode for what exactly? I reckon you can enable it for certain features. Unless I miss something new

**Comment by nkbt** [comment]
aha, loose:all.
Will test it in a moment.

**Comment by nkbt** [comment]
With loose:all everything seems working with no problems. Updated PR.

**Comment by chenglou** [comment]
Alright, this is going well =D

**Pull request merged**
