### PR TITLE
Color utils

### PR DESCRIPTION
**Pull request by threepointone**
copied from rebound-js

### CODE REVIEW

**Comment by chenglou** [comment]
Are we allowed to do this? lol license

**Comment by threepointone** [comment]
there, added the license :)

**Comment by iest** [comment]
Anything stopping this? Would love to use this "officially"...

**Comment by chenglou** [comment]
The new API from #129 might make this obsolete. We'll automatically transition between colors.

**Comment by iest** [comment]
:+1: 

Look forward to the new API!

**Comment by souporserious** [comment]
@threepointone I know this is super old, but I found someone that made a utility to help with this so I think this can be closed if you want https://github.com/germtb/color-interpolator

**Pull request closed without merging**
