### PR TITLE
Fix value for viewport

### PR DESCRIPTION
**Pull request by cody**

### CODE REVIEW

**Comment by nkbt** [comment]
:+1:

**Comment by chenglou** [comment]
So there were no such thing as just `scale`?
(Hey cody, I remember your profile picture =))

**Comment by cody** [comment]
@chenglou 
Safari complains that
> Viewport argument key "scale" not recognized and ignored.

and Chrome says:
> The key "scale" is not recognized and ignored.

The possible values for viewport are documented at MDN:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

**Comment by chenglou** [comment]
:+1:

**Pull request merged**
