### PR TITLE
Current positions is undefined at first render

### PR DESCRIPTION
**Pull request by peterssonjesper**
A bit nitty gritty, but it confused me when trying react-motion for the first time. I tried to do a similar thing as in this demo, but I used === instead (which doesn't eval as true for undefined and null, but == does).

### CODE REVIEW

**Comment by nkbt** [comment]
now at first render you check if there are any values and set your initial value if you want one.

**Comment by nkbt** [comment]
kind of
```js
  endValue(...args) {
    if (!args.length) {
      return {val: 0};
    }
    return {val: this.state.get('shouldClose') ? 0 : 1};
  },

// ...
      <Spring endValue={this.endValue}>
```

**Comment by chenglou** [comment]
Humm, `==` is used (and always used) for `null` and `undefined` check at once, and nowhere else. I'd like to keep it this way. Can you just change the comment to `undefined`?

**Comment by chenglou** [comment]
This does bring an issue that I've been thinking about. People keep asking how to do animation at mounting. This is the way to do it but it's not obvious enough. Maybe I _will_ release the `initialValue` prop after all.

**Comment by nkbt** [comment]
initial value is the great idea. I was thinking about adding it right 1 hour ago =)

**Comment by peterssonjesper** [comment]
@nkbt Yep, I realized that. Just confusing that the demo explicitly said that the argument is supposed to be null.

@chenglou I agree on the initialValue prop, that would probably be easier to understand.

**Comment by chenglou** [comment]
Oh sorry, didn't see you updated the PR. Thanks!

**Pull request merged**
