### PR TITLE
Support React 15

### LINKED ISSUE #317: React 15.0 support?
It's already RC2: https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

### PR DESCRIPTION
**Pull request by martijnrusschen**
This should fix #317

### CODE REVIEW

**Comment by nkbt** [comment]
Thanks @martijnrusschen, that will do the trick =)

**Comment by chenglou** [comment]
@nkbt We should put a note to merge to the development branch. Cherry picking (?) will be hard.

**Comment by troch** [comment]
@nkbt @chenglou will this be released? Ta!

**Comment by nkbt** [comment]
I don't think I have access to publish, so waiting for @chenglou :)

**Comment by chenglou** [comment]
@nkbt now you do! But gimme a sec. I wanna check if I can close a few issues first.

**Comment by nkbt** [comment]
\o/

**Comment by troch** [comment]
Thanks for releasing `0.4.3` :tada:

**Pull request merged**
