### PR TITLE
rename react lifecycle methods to prefix "UNSAFE_"

### PR DESCRIPTION
**Pull request by theopak**
hi @chenglou and @nkbt! what do you think of potentially shipping this quick rename? it comes from `$ npx react-codemod rename-unsafe-lifecycles` and would make the developer experience a little better for consumers that are on react v16.9, like we are at @Frameio

for anyone just catching up with this situation — please note that this rename fixes the console warnings introduced in react@16.9 such that code will run in react@17, but this rename _doesn't_ address the underlying issue

_edit:_ i pushed a config change just to get the build to pass, so please lmk if there's a different way that would work better here

### CODE REVIEW

**Comment by theopak** [comment]
_technically_ fixes #569

**Comment by theopak** [comment]
@nkbt awesome! i don't have merge permission though, can you merge this? 

yes, the eslint change was just to get the build to pass

**Comment by nkbt** [comment]
I've tested this PR and also check if built version works ok in one of my projects and everything seems to work well without React warnings. Merging in.

**Comment by nkbt** [comment]
Cannot publish until https://github.com/chenglou/react-motion/issues/577

**Comment by petrkrejcik** [comment]
Hi @nkbt, will you make a release with this change?

**Pull request merged**
